---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: infra-mariadb
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: master
  url: https://github.com/semii404/zopstix_demo
